### ISSUE TITLE
Serviço de Consulta de Parcelamento

### ISSUE THREAD

**Issue by gabriel-ecommet** [payu-br/bcash-java-sdk#10]
É necessária a criação de um serviço para consulta de parcelamento no cartão de crédito, para que os valores das taxas de parcelamento sejam exibidos corretamente para os clientes que implementam checkout transparente.

**Comment by rbatista** [comment]
Olá Gabriel,

O serviço de parcelamento foi desenvolvido na branch develop. Você pode utilizar a classe InstallmentService para isto.
Temos um exemplo no [README](https://github.com/payu-br/bcash-java-sdk/tree/develop#calculando-parcelamento) do projeto.
